# LAMPforge - LAMP Primer Designer - Conda Environment
# Save as: environment.yml

name: lamp_designer
channels:
  - conda-forge
  - defaults
  - bioconda

dependencies:
  # Core Python
  - python=3.8
  
  # Essential scientific computing
  - numpy>=1.19.0
  - scipy>=1.7.0
  
  # Machine Learning (optional but recommended)
  - scikit-learn>=0.24.0
  
  # Data manipulation and analysis
  - pandas>=1.3.0
  
  # Bioinformatics (optional for advanced features)
  - biopython>=1.79
  
  # Development and testing (optional)
  - pytest>=6.0.0
  - pytest-cov>=2.12.0
  
  
  # Plotting (optional for visualization)
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  
  # Additional utilities
  - tqdm>=4.62.0  # Progress bars
